export const publicAssets = new Map([
  ["/", ["index.html", "text/html"]],
  ["/index.html", ["index.html", "text/html"]],
  ["/styles.css", ["styles.css", "text/css"]],
  ["/app.js", ["app.js", "text/javascript"]],
  ["/auth-client.js", ["auth-client.js", "text/javascript"]],
  ["/access-gate.js", ["access-gate.js", "text/javascript"]],
  ["/theme.js", ["theme.js", "text/javascript"]],
  ["/ui.js", ["ui.js", "text/javascript"]],
  ["/workspace.js", ["workspace.js", "text/javascript"]],
  ["/experience.js", ["experience.js", "text/javascript"]],
  ["/validation.js", ["validation.js", "text/javascript"]],
  ["/results.js", ["results.js", "text/javascript"]],
  ["/evaluation-suites.js", ["evaluation-suites.js", "text/javascript"]],
  ["/human-review.js", ["human-review.js", "text/javascript"]],
  ["/review-view.js", ["review-view.js", "text/javascript"]],
  ["/context-summary.js", ["context-summary.js", "text/javascript"]],
  ["/backups.js", ["backups.js", "text/javascript"]],
  ["/training-state.js", ["training-state.js", "text/javascript"]],
  ["/workflow-receipt.mjs", ["workflow-receipt.mjs", "text/javascript"]],
  ["/training-guide.js", ["training-guide.js", "text/javascript"]],
  ["/training-client.js", ["training-client.js", "text/javascript"]],
  ["/playground-client.js", ["playground-client.js", "text/javascript"]],
  ["/playground.js", ["playground.js", "text/javascript"]],
  ["/favicon.svg", ["favicon.svg", "image/svg+xml"]],
]);
